languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Wordle, Illustrated"
description = "Daily Wordles, solved by me, illustrated by a bot."
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "January 2, 2006"

[params]
# mainSections = ["section1", "section2"]

[author]
name = "Genevieve"
image = "img/author.jpg"
headline = "I'm only human"
# bio = "A little bit about you"
